# Generated by Django 3.1.7 on 2021-03-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('last_year_qualified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'all_teams',
            },
        ),
    ]
