# Generated by Django 3.1.7 on 2021-03-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketGroups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamname',
            name='id',
        ),
        migrations.AlterField(
            model_name='teamname',
            name='team_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
